export const DATA = {
  users: [
    {
      id: 1,
      photo: "assets/1.jpeg",
      name: "Shivam Kumar",
      last_msg: "Reverse logic of Linked list is not that tough",
      time: "10:32 AM",
      count: 5,
    },
    {
      id: 2,
      photo: "assets/grp3.jpeg",
      name: "Family",
      last_msg: "Good Morning!",
      time: "06:25 AM",
      count: 1,
    },
    {
      id: 3,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      last_msg: "What is your plan for the Shivratri?",
      time: "09:39 PM",
      count: 0,
    },
    {
      id: 4,
      photo: "assets/3.jpeg",
      name: "Satyam Kumar",
      last_msg: "I do what I want.",
      time: "9:37 AM",
      count: 0,
    },
    {
      id: 5,
      photo: "assets/4.jpeg",
      name: "Pushpa Kumari",
      last_msg: "Semister exams are heading.",
      time: "8:45 AM",
      count: 0,
    },
    {
      id: 6,
      photo: "assets/5.jpeg",
      name: "Nivedita Mohapatra",
      last_msg: "When are you coming back?",
      time: "Yesterday",
      count: 0,
    },
    {
      id: 7,
      photo: "assets/6.jpeg",
      name: "Bhavani Shankar",
      last_msg: "We're planning for a trip to Hogenikal Falls tomorrow.",
      time: "Monday",
      count: 0,
    },
    {
      id: 8,
      photo: "assets/7.jpeg",
      name: "Kumkum Sahoo",
      last_msg: "I'll share you the link once I receive.",
      time: "29/01/2024",
      count: 0,
    },
    {
      id: 9,
      photo: "assets/8.jpeg",
      name: "Abhijeet Sahoo",
      last_msg: "Bro! I'm coming to BLR next weekend.",
      time: "22/01/2024",
      count: 0,
    },
    {
      id: 10,
      photo: "assets/9.jpeg",
      name: "Laxmi Priya",
      last_msg: "Where are you now?",
      time: "15/01/2024",
      count: 0,
    },
    {
      id: 11,
      photo: "assets/10.jpeg",
      name: "Debashish Hota",
      last_msg: "How are you Sambit?",
      time: "01/01/2024",
      count: 0,
    },
    {
      id: 12,
      photo: "assets/grp1.jpeg",
      name: "Friends",
      last_msg: "Gang! Let's plan for GOA for this summer. What say? All in?",
      time: "01/01/2024",
      count: 0,
    },
    {
      id: 13,
      photo: "assets/grp2.jpeg",
      name: "Childhood Friends",
      last_msg: "Get togater in next week at my place?",
      time: "27/12/2023",
      count: 0,
    },
    {
      id: 14,
      photo: "assets/grp4.jpeg",
      name: "Work Team",
      last_msg: "I'll be on leave today! I'll join back tomorrow!",
      time: "24/12/2023",
      count: 0,
    },
    {
      id: 15,
      photo: "assets/grp5.jpeg",
      name: "College Friends",
      last_msg: "Happy Birthday Sushree!!",
      time: "22/12/2023",
      count: 0,
    },
  ],
  self: {
    id: 16,
    photo: "assets/self.jpg",
    name: "Sambit Kumar",
  },
  messages: [
    {
      id: 1,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "Planning for a trip to Coimbatore Isha foundation",
      time: "10:32 AM",
    },
    {
      id: 2,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "on 8th March, i.e, Shivratri",
      time: "10:32 AM",
    },
    {
      id: 3,
      photo: "assets/self.jpg",
      name: "Sambit Kumar",
      msg: "Who all are in your plan?",
      time: "10:32 AM",
    },
    {
      id: 4,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "Solo planning",
      time: "10:32 AM",
    },
    {
      id: 5,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "will witness the grand Shivratri night long celebration ",
      time: "10:32 AM",
    },
    {
      id: 6,
      photo: "assets/self.jpg",
      name: "Sambit Kumar",
      msg: "Oh! Nice.",
      time: "10:32 AM",
    },
    {
      id: 7,
      photo: "assets/self.jpg",
      name: "Sambit Kumar",
      msg: "Thant happens on every year on Shivratri. They telecaste it live on youtube also so everyone can join virtually and enjoy the celebration.",
      time: "10:32 AM",
    },
    {
      id: 8,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "Yeah, but virtual can't match the live experience.",
      time: "10:32 AM",
    },
    {
      id: 9,
      photo: "assets/2.jpeg",
      name: "Puja Kumari",
      msg: "What is your plan for the Shivratri?",
      time: "10:32 AM",
    },
  ],
};
